### ISSUE TITLE
Create Register and Login page

### ISSUE THREAD

**Issue by mabartos** [528057/weather-app#2]
User should be able to provide his/her credentials. At least Username/email+password. We don't have to consider any other auth mechanisms.

Just get the necessary user info.

Authenticated user can:

Save locations, have favorites locations,...

We can have some sub-issues, just reference them here, or just have action items:
- [ ] Create components for login
- [ ] Create components for registration
- [ ] Provide auth mechanism

Mockup:

![abstract-surface-textures-white-concrete-stone-wall](https://github.com/528057/weather-app/assets/38039883/5db0e4e6-348a-440d-b9b3-d7c60f57d372)
